[package]
name = "tissue"
version = "0.1.0"
edition = "2021"

[dependencies]
antidote = "1.0.0"
clap = "3.0.14"
crossterm = "0.22.1"
git2 = "0.13.25"
human-panic = "1.0.3"
tempfile = "3.3.0"
toml = "0.5.8"
